services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ctrltee
    ports:
      - "5432:5432"
    volumes:
      - ctrltee-postgres-data:/var/lib/postgresql/data

volumes:
  ctrltee-postgres-data:
